# Generated by Django 3.2.13 on 2023-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yusmouser', '0002_auto_20230706_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_wallet_balance',
            field=models.IntegerField(default=0),
        ),
    ]
