# Generated by Django 3.2.13 on 2023-08-07 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yusmouser', '0003_customer_customer_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_wallet_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=13),
        ),
        migrations.CreateModel(
            name='MonnifyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionRefrence', models.CharField(max_length=1000)),
                ('paymentReference', models.CharField(max_length=1000)),
                ('amountPaid', models.CharField(max_length=1000)),
                ('totalPayable', models.CharField(max_length=1000)),
                ('settlementAmount', models.CharField(max_length=1000)),
                ('paidOn', models.CharField(max_length=1000)),
                ('paymentStatus', models.CharField(max_length=1000)),
                ('paymentDescription', models.CharField(max_length=1000)),
                ('currency', models.CharField(max_length=1000)),
                ('paymentMethod', models.CharField(max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
