# Generated by Django 3.2.13 on 2023-08-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yusmouser', '0004_auto_20230807_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
