# Generated by Django 3.2.13 on 2023-10-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yusmouser', '0005_alter_customer_customer_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monnifytransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yusmouser.customer'),
        ),
    ]
