# Generated by Django 3.2.13 on 2023-11-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yusmouser', '0007_airtime_cable_data_data_coupon_electricity_network_recharge_card_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='cableplan_amount',
        ),
        migrations.CreateModel(
            name='CablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cableplan_amount', models.CharField(max_length=200)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yusmouser.cable')),
            ],
        ),
    ]
