# Generated by Django 3.2.13 on 2023-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yusmouser', '0009_auto_20231127_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='cableplan_name',
            new_name='cable_name',
        ),
        migrations.AddField(
            model_name='cableplan',
            name='cable_plan_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
