"""
Django settings for yusmo project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
## = os.getenv('tj_secrets')
# my_secret = os.environ['tj_secrets']
MONNIFY_API_KEY = "MK_PROD_4RS9EEK7XF"
MONNIFY_SECRET_KEY = "UAP4GU0Z8GG6ANR6AVVCSG9AJJV81D7Q"
MONNIFY_BASE_URL = "https://api.monnify.com"
MONNIFY_WALLET_ACCOUNT_NUMBER = "8016575571"
MONNIFY_CONTRACT_CODE = "272745166491"
HUSMODATA_TOKEN = "3f9c7648318cb1cb26f56b0c2e0be18177bd77f3"
PAYSTACK_LIVE_PUBLIC_KEY = "pk_live_402c3cd3b991e90143c31bcd119f214e49b53280"
PAYSTACK_LIVE_SECRET_KEY = "sk_live_ed5adf0fef92b2067a3ad76255ce5c1a51f7c6a4"
PAYSTACK_TEST_SECRET_KEY = "sk_test_a6be918bcf48bb742c66a133101a8eee69032999"
PAYSTACK_TEST_PUBLIC_KEY = "pk_test_8cb6f341a2e78d65c6cbf23b05f253ef0c53f1e3"
HUSMODATA_API_TEST_TOKEN = "66f2e5c39ac8640f13cd888f161385b12f7e5e92"
HUSMODATA_API_KEY = "5880b91337684eb36e97f1b67be852b9bcec9d85"

SECRET_KEY = "W5d_aUr15rSIdi72hc78mIad6KVRqQ4sVovfJkLOzqs"
# SECRET_KEY = os.getenv('tj_secrets')

if SECRET_KEY is None:
    print(
        "Please setup a SECRET_KEY in the Secrets (Environment variables) tab. See README.md for more."
    )
    exit(1)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'yusmodata--tjib.repl.co', 'yusmodata.tjib.repl.co', '10.20.0.206','127.0.0.1'
]
X_FRAME_OPTIONS = '*'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #add the following
    #'signal_webhooks',
    'django.contrib.sites',
    'crispy_forms',
    'crispy_forms_bootstrap2',
    'django_extensions',
    'rest_framework',
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
    #'allauth.socialaccount.providers.google',  #for google auth
    'yusmouser'
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
       'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 
    'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIGNAL_WEBHOOKS = {
    "HOOKS": {
        "django.contrib.auth.models.User":...,
    },
}

""" SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
"""

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'yusmo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'yusmouser/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yusmo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# STATICFILES_DIRS = (
# BASE_DIR / 'yusmouser/static',)
STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'yusmouser/static']
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    #used for default signin such as loggin into admin panel
    'django.contrib.auth.backends.ModelBackend',

    #used for social authentications
    #'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1
LOGIN_URL = 'yusmouser:login'
LOGIN_REDIRECT_URL = 'yusmouser:login'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap"

CRISPY_TEMPLATE_PACK = "bootstrap"
# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ibrahimtijani08@gmail.com'  #your email-id
EMAIL_HOST_PASSWORD = 'qoollmurweuslqoh'  #your password
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# EMAIL_FILE_PATH = BASE_DIR / "sent_emails"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# APPEND_SLASH = False
CSRF_TRUSTED_ORIGINS = [
    'yusmodata--tjib.repl.co', 'https://yusmodata.tjib.repl.co/','yusmodata.tjib.repl.co', '127.0.0.1'
]
